services:
  redis:
    image: redis:alpine
    command: redis-server
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  api01: &api
    image: ghcr.io/kauefraga/bundemais:v1.5.0
    hostname: api01
    environment:
      - PORT=3001
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "120MB"
  api02:
    <<: *api
    hostname: api02
    environment:
      - PORT=3002
    ports:
      - "3002:3002"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
