# docker-compose.yml
services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1" # 10% de 1 CPU
          memory: "15MB"

  api1:

    # Using image for production

    &api
    image: juliapp/rinha-2025-elixir-vanilla:latest
    # using Dockerfile for local development
    # build: .
    hostname: api1
    environment:
      - APP_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    tty: true
    deploy:
      resources:
        limits:
          cpus: "0.6" # 60% de 1 CPU
          memory: "110MB"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 2s
      retries: 5

  api2:
    <<: *api
    hostname: api2

  redis:
    image: redis:7.2-alpine
    networks:
      - rinha-net
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "115MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
