services:
  api1: &api
    image: ghcr.io/chriscorrales/cash-fighter-api:latest
    hostname: api1
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - PORT=3000
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "80MB"

  api2:
    <<: *api
    hostname: api2

  worker1: &worker
    image: ghcr.io/chriscorrales/cash-fighter-worker:latest
    networks:
      - backend
      - payment-processor
    environment:
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "57.5MB"

  worker2:
    <<: *worker

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  load-balancer:
    image: nginx:latest
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "45MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true