services:
  redis:
    image: redis:alpine
    command: redis-server
    networks:
      - backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
    
  api01: &api
    image: ghcr.io/guisandroni/rinha-bun:latest
    hostname: api01
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT=${PAYMENT_PROCESSOR_DEFAULT:-http://localhost:8080}
      - PAYMENT_PROCESSOR_FALLBACK=${PAYMENT_PROCESSOR_FALLBACK:-http://localhost:8081}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    ports:
      - "3001:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "300MB"
  
  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"

networks:
  backend:
    driver: bridge
  payment-processor: {}
