services:
    api1: &api
        image: felipecassiano/api-rinha:latest
        environment:
            - REDIS_URL=redis://redis:6379
            - APP_PORT=3000
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    cpus: "0.15"
                    memory: "40MB"

    api2:
        <<: *api
        deploy:
            resources:
                limits:
                    cpus: "0.15"
                    memory: "40MB"

    worker:
        image: felipecassiano/worker-rinha:latest
        environment:
            - REDIS_URL=redis://redis:6379
            - PROCESSOR_DEFAULT=http://payment-processor-default:8080
            - PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    cpus: "0.80"
                    memory: "180MB"
    nginx:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "9999:9999"
        depends_on:
            - api1
            - api2
        deploy:
            resources:
                limits:
                    cpus: "0.20"
                    memory: "50MB"
        networks:
            - backend

    redis:
        image: redis:8.2-rc1-alpine
        ports:
            - "6379:6379"
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.20"
                    memory: "50MB"
networks:
    backend:
        driver: bridge
    payment-processor:
        external: true
