services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy-lb
    ports:
      - "9999:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - memsock:/tmp
    depends_on:
      - backend-1
      - backend-2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 210M
    restart: unless-stopped

  backend-1: &backend-template
    image: rodrigomilitao/rinha-go-in-memory:2025-v4
    ports:
      - "6061:6060"
    expose:
      - '8080'
    networks:
      - backend
      - payment-processor
    volumes:
      - memsock:/tmp
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080/payments
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - SOCKET_PATH=/tmp/api1.sock
      - OTHER_SOCKET_PATH=/tmp/api2.sock
      - SUMMARY_URL=http://app2:8080/internal/payments-summary
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '70MB'
    restart: unless-stopped

  backend-2:
    ports:
      - "6062:6060"
    environment:
      - SOCKET_PATH=/tmp/api2.sock
      - OTHER_SOCKET_PATH=/tmp/api1.sock  
      - SUMMARY_URL=http://app1:8080/internal/payments-summary
    <<: *backend-template

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

volumes:
  memsock:
