services:
  redis:
    image: redis:7-alpine
    container_name: rinha-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  api01:
    image: cicerocg/cgb-go-v2:latest
    platform: linux/amd64
    container_name: rinha-api01
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - PORT=80
      - REDIS_URL=redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "115MB"

  api02:
    image: cicerocg/cgb-go-v2:latest
    platform: linux/amd64
    container_name: rinha-api02
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - PORT=80
      - REDIS_URL=redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "115MB"

  nginx:
    image: nginx:1.27-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api01
      - api02
    networks:
      - rinha-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true