
services:
  api: &api
    container_name: api
    image: juanlimalf/api-payment_processor-rinha_backend_2025:redis-1.2
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - NUM_WORKERS=5
      - LOG_LEVEL=ERROR
    networks:
      - api
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 80M

  api2:
    <<: *api
    container_name: api2

  api3:
    <<: *api
    container_name: api3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api
    depends_on:
      - api
      - api2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  redis:
    image: redis:8-alpine
    container_name: redis
    command: [ "redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "60mb", "--maxmemory-policy", "allkeys-lru", "--io-threads", "1", "--io-threads-do-reads", "yes" ]
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 60M

networks:
  api:
    driver: bridge
  payment-processor:
    external: true
