services:
  rinha-redis:
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000 --maxmemory 80mb --maxmemory-policy allkeys-lru --tcp-backlog 65535
    hostname: rinha-redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  rinha-db:
    image: postgres:latest
    container_name: rinha-db
    hostname: rinha-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rinha
    networks:
      - backend
    ports:
      - "5432:5432"
    command:
      postgres
      -c max_connections=50
      -c shared_buffers=16MB
      -c effective_cache_size=32MB
      -c work_mem=1MB
      -c maintenance_work_mem=4MB
      -c synchronous_commit=off
      -c fsync=off
      -c wal_level=minimal
      -c max_wal_senders=0
      -c checkpoint_completion_target=0.9
      -c wal_buffers=1MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c min_wal_size=80MB
      -c max_wal_size=1GB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"
    volumes:
      - postgres-01:/var/run/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api-1: &api
    image: crispimgabriel/rinha-backend:latest
    hostname: api-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 45s
    environment:
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=postgres
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://rinha-db:5432/rinha
      - APP_PORT=8080
      - REDIS_URL=redis://rinha-redis:6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - BATCH_SIZE=30
      - EVENT_LOOPS_POOL_SIZE=4
    depends_on:
      rinha-db:
        condition: service_healthy
      rinha-redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "140MB"

  api-2:
    <<: *api
    hostname: api-2

  lb:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "10MB"

volumes:
  postgres-01:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true