
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '15mb'

  api1:
    image: glmsilva/rinha-de-backend-2025:latest
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha_db
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'


  api2:
    image: glmsilva/rinha-de-backend-2025:latest
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rinha_db
    depends_on:
      - postgres
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rinha_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha-network
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '135MB'

volumes:
  postgres_data:

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true
