x-rinha-api-base: &rinha-api-base
  image: jhamiltonjunior/rinha-go-escovando-bits-batch-insert:0.0.3
  volumes:
    - api-socketsv1:/tmp
  depends_on:
    - redis
  networks:
    - app-network
    - payment-processor
  deploy: &rinha-api-deploy
    resources:
      limits:
        cpus: "0.325"
        memory: "100MB"
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
  sysctls:
    net.core.somaxconn: 16384
    net.ipv4.tcp_max_syn_backlog: 16384
    net.ipv4.tcp_fin_timeout: 15
    net.ipv4.tcp_keepalive_time: 300
    net.ipv4.tcp_keepalive_intvl: 10
    net.ipv4.tcp_keepalive_probes: 5
    net.ipv4.tcp_max_tw_buckets: 65536
    net.ipv4.ip_local_port_range: 1024 65535
    net.ipv4.tcp_tw_reuse: 1

  environment: &common-environment
    # GOGC: 500
    APP_PORT: 3000
    REDIS_ADDR: redis:6379
    POSTGRES_URL: postgres://user:password-very-har@postgres:5432/rinha_de_backend?sslmode=disable
    NATS_URL: nats://nats:4222
    PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
    PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080

services:
  nginx:
    image: haproxy:3.2.3-alpine
    # image: nginx:stable-alpine
    container_name: nginx_load_balancer
    ports:
      - "9999:80"
    volumes:
      # - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - api-socketsv1:/tmp:rw
    depends_on:
      - rinha-api-1
      - rinha-api-2
      # - rinha-api-3
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: 16384
      net.ipv4.tcp_max_syn_backlog: 16384
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.tcp_keepalive_time: 300
      net.ipv4.tcp_keepalive_intvl: 10
      net.ipv4.tcp_keepalive_probes: 5
      net.ipv4.tcp_max_tw_buckets: 65536
      net.ipv4.ip_local_port_range: 1024 65535
      net.ipv4.tcp_tw_reuse: 1

  rinha-api-1:
    <<: *rinha-api-base
    container_name: rinha-api-1
    environment:
      <<: *common-environment
      RUN_VERIFY_PAYMENT_SERVICE: "true"
      UNIX_SOCKET: /tmp/api_1.sock
    command: ./main -socket /tmp/api_1.sock
    cpuset: "1,3"

  rinha-api-2:
    <<: *rinha-api-base
    container_name: rinha-api-2
    environment:
      <<: *common-environment
      UNIX_SOCKET: /tmp/api_2.sock
    command: ./main -socket /tmp/api_2.sock
    cpuset: "0,2"

  # rinha-api-3:
  #   <<: *rinha-api-base
  #   container_name: rinha-api-3
  #   environment:
  #     <<: *common-environment
  #     UNIX_SOCKET: /tmp/api_3.sock
  #   command: ./main -socket /tmp/api_3.sock

  # rinha-api-4:
  #   <<: *rinha-api-base
  #   container_name: rinha-api-4

  redis:
    image: redis:7.2.4-alpine
    container_name: redis_cache
    networks:
      - app-network
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "40MB"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      net.core.somaxconn: 16384
      net.ipv4.tcp_max_syn_backlog: 16384
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.tcp_keepalive_time: 300
      net.ipv4.tcp_keepalive_intvl: 10
      net.ipv4.tcp_keepalive_probes: 5
      net.ipv4.tcp_max_tw_buckets: 65536
      net.ipv4.ip_local_port_range: 1024 65535
      net.ipv4.tcp_tw_reuse: 1

  nats:
    image: nats:2.10.14-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  app-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  redis-data:
  api-socketsv1:
