name: rust-backend-spawn


x-api-base: &api-base
  image: jvsandrade/rust-backend-spawn:${DOCKER_TAG:-latest}
  depends_on:
    redis:
      condition: service_healthy
  networks:
    - rinha-net
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.5"
        memory: "100MB"

services:
  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.39"
          memory: "60MB"

  # API - Instância 1 (Líder)
  api01:
    <<: *api-base 
    hostname: api01
    environment:
      - NATS_URL=nats://nats:4222
      - DB_URL=redis://redis:6379
      - URL_DEFAULT=http://payment-processor-default:8080
      - URL_FALLBACK=http://payment-processor-fallback:8080
      - ROLE=LIDER 
      - AMBIENTE=PROD
      - NUM_CONSUMER=70
      - RETRY_DEFAULT_PERCENTAGE=90

  # API - Instância 2 (Colaboradora)
  api02:
    <<: *api-base 
    hostname: api02
    environment:
      - NATS_URL=nats://nats:4222
      - DB_URL=redis://redis:6379
      - URL_DEFAULT=http://payment-processor-default:8080
      - URL_FALLBACK=http://payment-processor-fallback:8080
      - ROLE=COLAB 
      - AMBIENTE=PROD
      - NUM_CONSUMER=70
      - RETRY_DEFAULT_PERCENTAGE=90

  # Fila de Mensagens
  nats:
    image: nats:2.11-alpine
    ports:
      - "4222:4222" 
      - "8222:8222" 
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD-SHELL", "nats server check"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "30MB"

  redis:
    image: redis:8-alpine
    hostname: redis
    ports:
      - "6379:6379" 
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
        resources:
          limits:
            cpus: "0.1"
            memory: "60MB"

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true