services:
  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    networks:
      - payment-processor
      - backend
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "30MB"

  postgres:
    container_name: postgres
    image: postgres:16.2-bookworm
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: >
      postgres -p 5432 
          -c max_wal_size=1GB 
          -c checkpoint_timeout=600 
          -c shared_buffers=256MB 
          -c max_connections=5000
          -c synchronous_commit=off
          -c log_statement=none
          -c commit_delay=100000
          -c fsync=off
          -c max_parallel_workers=0
          -c autovacuum=off
          -c log_duration=off
          -c log_checkpoints=0
          -c log_min_error_statement='panic'
    environment:
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - payment-processor
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "256MB"

  producer:
    container_name: producer
    hostname: producer
    image: nilferreira/anibalmf1-rinha-2025-producer
    ports:
      - "9999:9999"
    environment:
      APP_SERVER_URL: 0.0.0.0
      APP_SERVER_PORT: 9999
      # Server performance settings
      APP_SERVER_WORKERS: 1
      APP_SERVER_MAX_CONNECTIONS: 10000
      APP_SERVER_BACKLOG: 32768
      APP_SERVER_CLIENT_TIMEOUT: 1000
      APP_SERVER_KEEP_ALIVE: 1000
      # Database pool settings
      # Service URLs
      APP_REDIS_URL: redis://redis:6379
      APP_PAYMENT_TOPIC: payment
      APP_QUEUE_WORKERS: 1
      # Database connection
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: postgres
      APP_DATABASE_USER: postgres
      APP_DATABASE_PASSWORD: postgres
    networks:
      - payment-processor
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      consumer:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "32MB"

  consumer:
    container_name: consumer
    hostname: consumer
    image: nilferreira/anibalmf1-rinha-2025-consumer
    environment:
      APP_REDIS_URL: redis://redis:6379
      APP_PAYMENT_TOPIC: payment
      APP_QUEUE_WORKERS: 150
      APP_DATABASE_HOST: postgres
      APP_DATABASE_PORT: 5432
      APP_DATABASE_NAME: postgres
      APP_DATABASE_USER: postgres
      APP_DATABASE_PASSWORD: postgres
      APP_PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      APP_PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
    networks:
      - payment-processor
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "32MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
