version: '3.8'

services:
  api-1:
    image: caminhacaio/rinha-backend-kotlin-spring-native:18.0-amd
    environment:
      SERVER_PORT: 8080
      INTERNAL_BACKEND_URL: http://api-2:8080
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '140MB'
  api-2:
    image: caminhacaio/rinha-backend-kotlin-spring-native:18.0-amd
    environment:
      SERVER_PORT: 8080
      INTERNAL_BACKEND_URL: http://api-1:8080
      PAYMENT_PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: '140MB'

  load-balancer:
    image: nginx:alpine
    restart: always
    container_name: rinha-load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.26"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true