services:
  db:
    container_name: db
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./config/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"
  payment-processor-lb:
    image: nginx:alpine
    container_name: payment-processor-lb
    ports:
        - "9999:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
        - backend
    depends_on:
        - payment-processor-mid-1
        - payment-processor-mid-2
    deploy:
        resources:
          limits:
              cpus: '0.2'
              memory: '10MB'
  payment-processor-mid-1: &api
    container_name: payment-processor-mid-1
    hostname: payment-processor-mid-1
    image: danielmods/api-rinha-3:1
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "10000:80"
    networks:
      - backend
      - payment-processor
    depends_on:
      - db
      - payment-processor-mid-health-check
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '110MB'
  payment-processor-mid-2:
    <<: *api 
    container_name: payment-processor-mid-2
    hostname: payment-processor-mid-2
    ports:
      - "10001:80"
  payment-processor-mid-health-check:
    container_name: payment-processor-mid-health-check
    hostname: payment-processor-mid-health-check
    image: danielmods/worker-healthcheck-rinha-3:1
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "10002:80"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'
  
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


