services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  api1: &api
    image: eduardofp/rinha-backend
    hostname: api1
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - UV_THREADPOOL_SIZE=16
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "120MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - UV_THREADPOOL_SIZE=16

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - rinha-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"


networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true