services:
  api1:
    image: queijocoalho/rinha2025:1.0.0
    container_name: api1
    expose:
      - "9999"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : master
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
      GOMAXPROCS: 1 
      WORKERS: 4
      POOLSIZE: 5000
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "125MB"

  api2:
    image: queijocoalho/rinha2025:1.0.0
    container_name: api2
    expose:
      - "9999"
    networks:
      - backend
      - payment-processor
    environment:
      NAME : slave
      PAYMENT_URL_DEFAULT: "http://payment-processor-default:8080/payments"
      PAYMENT_URL_FALLBACK: "http://payment-processor-fallback:8080/payments"
      GOMAXPROCS: 1 
      WORKERS: 4
      POOLSIZE: 5000
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "125MB"

  haproxy:
    image: haproxy:3.2.3-alpine3.22
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true