services:
  api1:
    image: pedrohsbarbosa99/rinha-fastapi-2025:0.2.2
    command: uvicorn app.apis.main:app --host 0.0.0.0 --port 9999 --workers 1 --loop uvloop --http httptools --no-access-log
    networks:
      - backend
      - payment-processor
    environment:
      - SUMMARY_URL=http://api2:9999/internal/payments-summary
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "100M"

  api2:
    image: pedrohsbarbosa99/rinha-fastapi-2025:0.2.2
    command: uvicorn app.apis.main:app --host 0.0.0.0 --port 9999 --workers 1 --loop uvloop --http httptools --no-access-log
    networks:
      - backend
      - payment-processor
    environment:
      - SUMMARY_URL=http://api1:9999/internal/payments-summary
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "100M"

  nginx:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "150M"
    networks:
      - backend


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
