version: "3.8"

services:
  nginx:
    user: root
    image: eddiendulo/monitor-nginx
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 5s
      timeout: 2s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  app1:
    image: eddiendulo/monitor-app1
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/rinha
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WORKERS=${WORKERS:-8}
      - QUEUE_SIZE=${QUEUE_SIZE:-2000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  app2:
    image: eddiendulo/monitor-app2
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/rinha
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - WORKERS=${WORKERS:-8}
      - QUEUE_SIZE=${QUEUE_SIZE:-2000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

volumes:
  pg_data: