services:

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  db-rinha:
    image: postgres:16
    container_name: rinha-mvc-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "40MB"

  api-1:
    image: annicoletti/rinha-router-mvc:latest
    container_name: rinha-router-mvc-api-1
    depends_on:
      - db-rinha
      - nginx
    env_file:
      - .env
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

  api-2:
    image: annicoletti/rinha-router-mvc:latest
    container_name: rinha-router-mvc-api-2
    depends_on:
      - db-rinha
      - nginx
    env_file:
      - .env
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "150MB"

volumes:
  pgdata:

networks:
  payment-processor:
    external: true