services:
  api1:
    image: mbenencase96/rinha-de-backend-2025-fastapi:latest
    hostname: api1
    environment:
      - DATABASE_URL=postgresql+asyncpg://rinha:rinha@db/rinha
      - REDIS_URL=redis://redis
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - db
      - redis
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api2:
    image: mbenencase96/rinha-de-backend-2025-fastapi:latest
    hostname: api2
    environment:
      - DATABASE_URL=postgresql+asyncpg://rinha:rinha@db/rinha
      - REDIS_URL=redis://redis
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      - db
      - redis
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  # Load Balancer
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
          
  redis:
    image: redis:7.2-alpine
    hostname: redis
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

volumes:
  pgdata:

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true