services:
  backbone:
    image: davidbeyda/rinha-backbone:latest
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 160M
    networks:
      - internal
      - payment-processor

  frontend1:
    image: davidbeyda/rinha-frontend:latest
    environment:
      - GRPC_SERVICE_ADDR=backbone:8080
      - HTTP_PORT=8081
    expose:
      - "8081"
    depends_on:
      - backbone
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40M
    networks:
      - internal

  frontend2:
    image: davidbeyda/rinha-frontend:latest
    environment:
      - GRPC_SERVICE_ADDR=backbone:8080
      - HTTP_PORT=8082
    expose:
      - "8082"
    depends_on:
      - backbone
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 40M
    networks:
      - internal

  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend1
      - frontend2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 110M
    networks:
      - internal

networks:
  internal:
    driver: bridge
  payment-processor:
    external: true