x-api: &payment-api-template
  # build: ./payment-api
  image: mauriciocantu/payment-api:v3
  depends_on:
    redis:
      condition: service_healthy
  networks:
    - rinha-backend
    - payment-processor

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-api-01
      - payment-api-02
    ports:
      - "9999:9999"
    networks:
      - rinha-backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  payment-api-01:
    <<: *payment-api-template
    hostname: payment-api-01
    container_name: payment-api-01
    environment:
      - PAYMENTS_QUEUE=${PAYMENTS_QUEUE}
      - REDIS_URL=${REDIS_URL}
      - PROCESS_PAYMENT_JOB_NAME=${PROCESS_PAYMENT_JOB_NAME}
      - PAYMENT_PROCESSOR_URL_DEFAULT=${PAYMENT_PROCESSOR_URL_DEFAULT}
      - PAYMENT_PROCESSOR_URL_FALLBACK=${PAYMENT_PROCESSOR_URL_FALLBACK}
      - HTTP_CONNECTIONS_NUMBER=${HTTP_CONNECTIONS_NUMBER}
      - BATCH_CONCURRENCY=${BATCH_CONCURRENCY_API_1}
      - BATCH_INTERVAL=${BATCH_INTERVAL}
      - FOREIGN_API_URL=http://payment-api-02:3000
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "135MB"

  payment-api-02:
    <<: *payment-api-template
    hostname: payment-api-02
    container_name: payment-api-02
    environment:
      - PAYMENTS_QUEUE=${PAYMENTS_QUEUE}
      - REDIS_URL=${REDIS_URL}
      - PROCESS_PAYMENT_JOB_NAME=${PROCESS_PAYMENT_JOB_NAME}
      - PAYMENT_PROCESSOR_URL_DEFAULT=${PAYMENT_PROCESSOR_URL_DEFAULT}
      - PAYMENT_PROCESSOR_URL_FALLBACK=${PAYMENT_PROCESSOR_URL_FALLBACK}
      - HTTP_CONNECTIONS_NUMBER=${HTTP_CONNECTIONS_NUMBER}
      - BATCH_CONCURRENCY=${BATCH_CONCURRENCY_API_2}
      - BATCH_INTERVAL=${BATCH_INTERVAL}
      - FOREIGN_API_URL=http://payment-api-01:3000
      - RUN_HEALTHCHECK=true
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "155MB"

  redis:
    image: redis:8.2-alpine
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"
    networks:
      - rinha-backend

networks:
  rinha-backend:
    driver: bridge
  payment-processor:
    external: true
