version: '3.8'

services:
  app1:
    restart: always
    image: docker.io/gustavodocker910/rinha-backend-25:1.1.1
    hostname: app1
    environment:
      - JAVA_OPTS=-Xmx128m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - INSTANCE_ID=API-1
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "130MB"
    networks:
      - payment-processor

  app2:
    restart: always
    image: docker.io/gustavodocker910/rinha-backend-25:1.1.1
    hostname: app2
    environment:
      - JAVA_OPTS=-Xmx128m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - INSTANCE_ID=API-2
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "130MB"
    networks:
      - payment-processor

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
    networks:
      - payment-processor

  redis:
    image: redis:8.0.3-alpine
    container_name: db-payment-redis
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory-policy noeviction
    ports:
      - 6379:6379
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "75MB"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h 127.0.0.1 ping || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  payment-processor:
    external: true



