services:
  api1:
    image: jrblatt/rinha-de-backend-2025-nodejs:1.0.0
    container_name: api1
    hostname: api1
    environment:
      - MODE=💩
      - WORKERS=1
      - FALLBACK_INTERVAL=5
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: 150MB

  api2:
    image: jrblatt/rinha-de-backend-2025-nodejs:1.0.0
    container_name: api2
    hostname: api2
    environment:
      - MODE=💩
      - WORKERS=1
      - FALLBACK_INTERVAL=5
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: 150MB

  beercache:
    image: jrblatt/beercache:1.0.0
    container_name: beercache
    volumes:
      - rb2025:/tmp/
    networks:
      - payment-processor
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 30MB

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - rb2025:/tmp/
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

volumes:
  rb2025:
    driver: local

networks:
  payment-processor:
    external: true
    driver: bridge
