services:
  service1: &service
    image: willian666/rinha-back-node-2025:v0.7
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - NODE_ENV=production
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "fetch('http://localhost:3333/healthcheck').then(res => process.exit(res.ok ? 0 : 1)).catch(() => process.exit(1))"
        ]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"

  service2:
    <<: *service

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
    - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "60MB"
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "90MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true