services:

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  api1: &api
    image: vctrhugo3011/rinha2025-api:latest
    hostname: api1
    networks:
      - backend
      - payment-processor
    depends_on:
      - worker1
      - worker2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "70MB"

  api2:
    <<: *api
    hostname: api2

  worker1: &worker
    image: vctrhugo3011/rinha2025-worker:latest
    container_name: worker1
    environment:
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - WORKER_CONCURRENCY=20
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  worker2:
    <<: *worker
    container_name: worker2

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
