version: '3.8'

services:
  redis:
    image: redis:7-alpine
    networks:
      - backend
      - payment-processor
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

  health:
    image: djbrunomonteiro/rinha-backend-2025:latest
    command: ["node", "./dist/workers/health.js"]
    depends_on:
      redis:
        condition: service_started
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.01"
          memory: "15MB"

  app1:
    image: djbrunomonteiro/rinha-backend-2025:latest
    hostname: app1
    depends_on:
      health:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "1.09"
          memory: "150MB"

  app2:
    image: djbrunomonteiro/rinha-backend-2025:latest
    hostname: app2
    depends_on:
      health:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "90MB"

  load-balancer:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    depends_on:
      app1:
        condition: service_started
      app2:
        condition: service_started      
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "75MB"

networks:
  backend:
    driver: bridge

  payment-processor:
    external: true
