x-service-templates:
  api: &api
    image: teuso99/teuso-rinha-2025:1.0
    networks:
      - rinha
      - payment-processor
    environment:
      - URL_REDIS=queue:6379
      - URL_DEFAULT=http://payment-processor-default:8080
      - URL_FALLBACK=http://payment-processor-fallback:8080
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=rinha;Username=usr_rinha;Password=123
    depends_on:
      - db
      - queue
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "90MB"

services:

#--- LOAD BALANCER ---
  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  queue:
    image: redis:8.0-alpine
    container_name: queue
    hostname: queue
    networks:
      - rinha
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10MB"
    
#--- APIs ---          
  api01:
    <<: *api
    container_name: api01
    hostname: api01

  api02:
    <<: *api
    container_name: api02
    hostname: api02

#--- DB ---
  db:
    container_name: db
    hostname: db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=usr_rinha
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=rinha
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "110MB"

networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true