version: "3.8"

services:
  app1:
    image: guianacleto/rinha-backend-2025:1.0
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "162MB"

  app2:
    image: guianacleto/rinha-backend-2025:1.0  # usa a mesma imagem já buildada pelo app1
    networks:
      - backend
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080/payments
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "162MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "25MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
