services:
  db:
    image: postgres:16.2
    hostname: db
    volumes:
      - ./postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
    environment:
      - POSTGRES_DB=rinha
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  api01: &api
    image: gui9394/rinha-de-backend-2025-q3:0.3.0-SNAPSHOT
    hostname: api01
    environment:
      - LOG_LEVEL=OFF
      - SERVER_PORT=8080
      - POSTGRES_DB=rinha
      - POSTGRES_HOST=db:5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - PROCESS-PAYMENT_QUEUE_CONSUMER=10
      - PROCESS-PAYMENT_QUEUE_SIZE-MIN=20
      - PROCESS-PAYMENT_QUEUE_ENQUEUE-DELAY=120
      - PAYMENT-PROCESSOR_DEFAULT_BASE-URL=http://payment-processor-default:8080
      - PAYMENT-PROCESSOR_FALLBACK_BASE-URL=http://payment-processor-fallback:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "135MB"

  api02:
    <<: *api
    hostname: api02

  gateway:
    image: nginx:1.25.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - rinha
      - payment-processor
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  payment-processor:
    external: true
  rinha:
    driver: bridge
