version: "3.5"
x-service-templates:
  backend-api: &backend-api
    image: ghcr.io/marincor/rinha-backend-2025-golang:latest
    environment:
      SERVER_PORT: 5000
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      REDIS_URL: redis:6379
    networks:
      - payment-processor
      - backend
      - redis-network
    depends_on:
      - redis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "135MB"


services:
  api01:
    <<: *backend-api
    container_name: api01
    hostname: api01

  api02:
    <<: *backend-api
    container_name: api02
    hostname: api02

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - redis-network
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    networks:
      - backend
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
  redis-network:
    driver: bridge