networks:
    backend:
        driver: bridge
    payment-processor:
        name: payment-processor
        external: true
services:
    api1:
        image: mxlange/api-cpp:v1.0.0
        hostname: api1
        environment:
            - API_INSTANCES=http://api2:8080
            - BASE_URL_DEFAULT=http://payment-processor-default:8080
            - BASE_URL_FALLBACK=http://payment-processor-fallback:8080
            - WORKERS=10
        networks:
            - payment-processor
            - backend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://api1:8080/health"]
            interval: 1s
            timeout: 3s
            retries: 10
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "150MB"
    api2:
        image: mxlange/api-cpp:v1.0.0
        hostname: api2
        environment:
            - API_INSTANCES=http://api1:8080
            - BASE_URL_DEFAULT=http://payment-processor-default:8080
            - BASE_URL_FALLBACK=http://payment-processor-fallback:8080
            - WORKERS=10
        networks:
            - payment-processor
            - backend
        healthcheck:
            test: ["CMD", "curl", "-f", "http://api2:8080/health"]
            interval: 1s
            timeout: 3s
            retries: 10
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "150MB"
    nginx:
        image: nginx:1.25-alpine
        container_name: rinha-nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "9999:9999"
        networks:
            - backend
        depends_on:
            api1:
                condition: service_healthy
            api2:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "50MB"
