version: '3.8'

x-services-templates:
  backend-app: &backend-app
    image: docker.io/jairoandre/rb2025-v2:latest
    networks:
      - backend
      - payment-processor
    depends_on:
      - service-health
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

services:
  # Load Balancer / API Gateway
  service-health:
    image: docker.io/jairoandre/rb2025-health:latest
    container_name: service-health
    networks:
      - backend
      - payment-processor
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  # Backend Instance 1
  backend1:
    <<: *backend-app
    container_name: backend1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - HEALTH_URL=http://service-health:9001
      - OTHER_BACKEND=http://backend2:9999
  # Backend Instance 2
  backend2:
    <<: *backend-app
    container_name: backend2
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - HEALTH_URL=http://service-health:9001
      - OTHER_BACKEND=http://backend1:9999

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true

