services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - payment-01
      - payment-02
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '20MB'
  payment-queue:
    image: redis:alpine
    container_name: payment-queue
    hostname: payment-queue
    networks:
      - backend
    ports:
      - '6379:6379'
    environment:
      - REDIS_HOST=payment-queue
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '50MB'
  db:
    image: postgres:alpine
    container_name: db
    hostname: db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '70MB'

  payment-01: &payment-01
    # build:
    # context: ../payments
    # dockerfile: Dockerfile
    image: alvesa/rinha-backend-2025:latest
    container_name: payment-01
    hostname: payment-01
    expose:
      - '8080'
    environment:
      - PORT=8080
      - BASE_URL_PAYMENT_PROCESSOR=http://payment-processor-default:8080
      - BASE_URL_PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_PORT=6379
      - REDIS_HOST=payment-queue
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    networks:
      - backend
      - payment-processor
    depends_on:
      - payment-queue
      - db
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '100MB'
  payment-02:
    <<: *payment-01
    container_name: payment-02
    hostname: payment-02
networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true
