x-api-template: &api-template
  image: adrianomoreira86/rinha-de-backend-2025-java-quarkus-api:final
  networks:
    - app
    - payment-processor
  depends_on:
    postgres:
      condition: service_healthy
  environment:
    quarkus.datasource.db-kind: postgresql
    quarkus.datasource.username: admin
    quarkus.datasource.password: 123
    quarkus.datasource.reactive.url: vertx-reactive:postgresql://postgres:5432/rinha
    quarkus.datasource.jdbc.max-size: 50

x-worker-template: &worker-template
  image: adrianomoreira86/rinha-de-backend-2025-java-quarkus-worker:latest
  networks:
    - app
    - payment-processor
  depends_on:
    postgres:
      condition: service_healthy
  environment:
    quarkus.datasource.db-kind: postgresql
    quarkus.datasource.username: admin
    quarkus.datasource.password: 123
    quarkus.datasource.reactive.url: vertx-reactive:postgresql://postgres:5432/rinha
    quarkus.datasource.jdbc.max-size: 20 #20 is default
    quarkus.rest-client.processor-default.url: http://payment-processor-default:8080/
    quarkus.rest-client.processor-fallback.url: http://payment-processor-fallback:8080/
    quarkus.log.level: INFO

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: ".2"
          memory: "48MB"

  api-1:
    <<: *api-template
    deploy:
      resources:
        limits:
          cpus: ".3"
          memory: "48MB"
  api-2:
    <<: *api-template
    deploy:
      resources:
        limits:
          cpus: ".3"
          memory: "48MB"
  worker-1:
    <<: *worker-template
    deploy:
      resources:
        limits:
          cpus: ".4"
          memory: "48MB"

  postgres:
    image: postgres:17
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "rinha", "-U", "admin" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql:ro
    deploy:
      resources:
        limits:
          cpus: ".3"
          memory: "158MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
