services:
  service1: &service
    image: willian666/rinha-back-lua-2025:v0.2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:3333/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  service2:
    <<: *service
    environment:
      - HEALTH_CHECK_ENABLED=1
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
  
  service3:
    <<: *service

  service4:
    <<: *service
  
  service5:
    <<: *service

  service6:
    <<: *service
  
  service7:
    <<: *service
  
  service8:
    <<: *service

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
    - 6379:6379
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "60MB"
    networks:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      service1:
        condition: service_healthy
      service2:
        condition: service_healthy
      service3:
        condition: service_healthy
      service4:
        condition: service_healthy
      service5:
        condition: service_healthy
      service6:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true


    