services:
  bg-api-1: &bg-api
    image: josafaverissimo/boogie-woogie-pay-api:latest
    hostname: bg-api-1
    networks:
      - bg-api
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - X_RINHA_TOKEN=123
    depends_on:
      - bg-valkey
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "110MB"

  bg-api-2:
    <<: *bg-api
    hostname: bg-api-2

  worker-1: &worker
    image: josafaverissimo/boogie-woogie-pay-worker:latest
    hostname: bg-worker-1
    networks:
      - bg-api
      - payment-processor
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - X_RINHA_TOKEN=123
    depends_on:
      - bg-valkey
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - bg-api
    depends_on:
      - bg-api-1
      - bg-api-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
  
  bg-valkey:
    image: valkey/valkey:8.1.3-alpine
    hostname: bg-valkey
    networks:
      - payment-processor
      - bg-api
    ports:
      - "9927:6379"
    volumes:
      - bgpay-valkey-data:/data
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

networks:
  bg-api:
    driver: bridge
  payment-processor:
    external: true

volumes:
  bgpay-valkey-data:
