services:
  # Serviço 1
  figth-1:
    image: ghcr.io/camilocoelhogomes/backend-fight-2025:0.0.2
    container_name: service_1
    restart: unless-stopped
    environment: &figth-env
      - DB_URL=jdbc:postgresql://postgres:5432/figth_db
      - DB_USER=figth_user
      - DB_PASSWORD=figth_password
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL=OFF
      - HIKARI_MAX_POOL_SIZE=100
      - HIKARI_MIN_IDLE=10
      - HIKARI_CONNECTION_TIMEOUT=5000
      - HIKARI_IDLE_TIMEOUT=300000
      - HIKARI_MAX_LIFETIME=900000
      - HIKARI_LEAK_DETECTION=30000
      - HIBERNATE_SHOW_SQL=false
      - HIBERNATE_FORMAT_SQL=true
      - HIBERNATE_USE_SQL_COMMENTS=false
      - PROCESS_STRATEGY=queue
      - PAYMENT_QUEUE_PROCESSOR_BATCH_SIZE=100
      - PAYMENT_QUEUE_PROCESSOR_TIMEOUT=3
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - figth-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 90M

  # Serviço 2 - reutiliza as mesmas variáveis de ambiente
  figth-2:
    image: ghcr.io/camilocoelhogomes/backend-fight-2025:0.0.2
    container_name: service_2
    restart: unless-stopped
    environment: *figth-env  # Reutiliza as mesmas variáveis
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - figth-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: 0.4
          memory: 90M

  nginx:
    image: nginx:alpine
    container_name: figth-nginx
    restart: unless-stopped
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - figth-1
      - figth-2
    networks:
      - figth-network
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 10M

  postgres:
    image: postgres:17-alpine
    container_name: figth-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: figth_db
      POSTGRES_USER: figth_user
      POSTGRES_PASSWORD: figth_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-collate=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - figth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U figth_user -d figth_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: 0.6
          memory: 160M

volumes:
  portainer_data:
  postgres_data:
    driver: local

networks:
  figth-network:
    driver: bridge
  payment-processor:
    external: true 