
x-backend-template: &backend-template
  depends_on:
    - redis
  networks:
    - backend
    - payment-processor
  environment:
    - APP_DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
    - APP_FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
    - APP_REDIS_URL=redis://redis:6379
    - APP_SERVER_KEEPALIVE=500
    - APP_PAYMENT_PROCESSOR_WORKER_COUNT=6
  deploy:
    resources:
      limits:
        cpus: "0.50"
        memory: "100MB"

x-nginx-template: &nginx-template
  image: nginx:latest
  hostname: nginx
  ports:
    - "9999:9999"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.25"
        memory: "100MB"

services:
  nginx:
    <<: *nginx-template
    hostname: nginx
    container_name: rinha-nginx
    depends_on:
      - backend-01
      - backend-02

  backend-01:
    <<: *backend-template
    image: ghcr.io/josimar-silva/rinha-de-backend-2025:0.5.0
    hostname: backend-01
    container_name: rinha-backend-01

  backend-02:
    <<: *backend-template
    image: ghcr.io/josimar-silva/rinha-de-backend-2025:0.5.0
    hostname: backend-02
    container_name: rinha-backend-02

  redis:
    image: redis:8.2.0-alpine
    hostname: redis
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
