services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "80MB"

  app01: &api
    image: carlosdemarco/rinha-backend-2025:latest
    container_name: ms-payments-01
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/payments_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      LOG_SQL: "false"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/q/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - payment-processor
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

  app02:
    <<: *api
    container_name: ms-payments-02
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/payments_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      PAYMENT_PROCESSOR_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_FALLBACK: http://payment-processor-fallback:8080
      LOG_SQL: "false"
    networks:
      - payment-processor
      - backend-network

  nginx:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend-network
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  payment-processor:
    external: true
  backend-network:
    driver: bridge