services:
  api1: &api
    image: gabrielluciano/rinha-2025-quarkus:1.0.1
    hostname: api1
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      - HTTP_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL=OFF
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - HTTP_PORT=8081
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - LOG_LEVEL=OFF

  redis:
    image: redis:8.2.0
    hostname: redis
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 50mb
      --maxmemory-policy allkeys-lru
      --maxclients 1000
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  nginx:
    image: nginx:1.29.1
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
