version: '3.8'

services:
  # Aplicao principal - 2 instancias para load balancing
  app1:
    image: joneysousa/rinha-backend-2025-python:latest
    container_name: python-rinha-app1
    ports:
      - "9999"
    environment:
      - DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor:8080
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/payments
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"
    networks:
      - rinha-network
      - payment-processor

  app2:
    image: joneysousa/rinha-backend-2025-python:latest
    container_name: python-rinha-app2
    ports:
      - "9999"
    environment:
      - DEFAULT_PAYMENT_PROCESSOR_URL=http://payment-processor:8080
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://user:password@postgres:5432/payments
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"
    networks:
      - rinha-network
      - payment-processor

  # Load Balancer (Nginx)
  nginx:
    image: nginx:alpine
    container_name: python-rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    networks:
      - rinha-network

  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: python-rinha-postgres
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "80MB"
    networks:
      - rinha-network
      - payment-processor

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: python-rinha-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"
    networks:
      - rinha-network
      - payment-processor

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres_data:
  redis_data:
