services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    restart: always
    networks:
      - payment-proxy
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "20MB"

  payment-proxy-1: &proxy1
    image: igormsoares/rinha-2025-payment-proxy
    container_name: payment-proxy-1
    hostname: payment-proxy-1
    restart: always
    environment:
      - GOMAXPROCS=1
      - DISPATCHER_REDIS_POOL=60
      - COST_WEIGHT=0.75
      - LATENCY_LIMIT=100ms
      - LB_CIRCUIT_TIMEOUT=1.5s
      - CB_RECOVERY_TIMEOUT=0.5s
      - CB_RECOVERY_ATTEMPTS=50
      - CB_FAILURE_THRESHOLD=5
      - PROCESSOR_REQ_TIMEOUT=10s
      - MAX_WORKERS=15
    networks:
      - payment-proxy
      - payment-processor
    depends_on:
      - nginx
      - redis
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "95MB"

  payment-proxy-2:
    <<: *proxy1
    container_name: payment-proxy-2
    hostname: payment-proxy-2
    environment:
      - GOMAXPROCS=1
      - DISPATCHER_REDIS_POOL=60
      - COST_WEIGHT=0.75
      - LATENCY_LIMIT=100ms
      - LB_CIRCUIT_TIMEOUT=1.5s
      - CB_RECOVERY_TIMEOUT=0.5s
      - CB_RECOVERY_ATTEMPTS=50
      - CB_FAILURE_THRESHOLD=5
      - PROCESSOR_REQ_TIMEOUT=10s
      - MAX_WORKERS=15

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    command: >
      redis-server
        --maxclients 1000
        --maxmemory 140mb
        --save ""
        --appendonly no
        --timeout 0
        --databases 1
        --tcp-keepalive 300
        --tcp-backlog 3072
        --client-output-buffer-limit normal 0 0 0
        --io-threads 4
        --io-threads-do-reads yes
    networks:
      - payment-proxy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "140MB"

networks:
  payment-proxy:
    driver: bridge
  payment-processor:
    external: true


