services:
  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    ports:
      - "9999:80"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

  api01: &api
    hostname: api01
    image: rodscaldeira/rinha_backend_2025:202508032036
    networks:
      - rinha
      - payment-processor
    environment:
      - WORKER_POOL_SIZE=20
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
      - RELEASE_NODE=api01@api01
      - RELEASE_COOKIE=rinha
      - CLUSTER_NODE=api02@api02
      - ERL_MAX_PORTS=4096
    healthcheck:
      test: curl -f http://api01:4000/health-check
      timeout: 15s
      start_period: 30s
      start_interval: 1s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "170MB"

  api02:
    <<: *api
    hostname: api02
    environment:
      - WORKER_POOL_SIZE=20
      - DEFAULT_SERVICE_NAME=default
      - DEFAULT_SERVICE_URL=http://payment-processor-default:8080
      - FALLBACK_SERVICE_NAME=fallback
      - FALLBACK_SERVICE_URL=http://payment-processor-fallback:8080
      - RELEASE_NODE=api02@api02
      - RELEASE_COOKIE=rinha
      - CLUSTER_NODE=api01@api01
      - ERL_MAX_PORTS=4096
    healthcheck:
      test: curl -f http://api02:4000/health-check
      timeout: 15s
      start_period: 30s
      start_interval: 1s
      retries: 3

networks:
  rinha:
    name: rinha
    driver: bridge
  payment-processor:
    external: true
