services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api01
      - api02
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30mb"
  api01:
    image: dmorais15/rinha-2025-backend-native:8.0-od
    container_name: api01
    networks:
      - backend
      - payment-processor
    environment:
      - URL1=http://payment-processor-default:8080
      - OTHER_API=http://api02:8080
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"
  api02:
    image: dmorais15/rinha-2025-backend-native:8.0-od
    container_name: api02
    networks:
      - backend
      - payment-processor
    environment:
      - URL1=http://payment-processor-default:8080
      - OTHER_API=http://api01:8080
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
