services:
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    volumes:
      - ./nginx.config:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"

  api1: &api
    image: marceloorsa/rinha-rust:1.0.0
    hostname: api1
    environment:
      - REDIS_URI=redis://redis:6379/
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8001/payments
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8002/payments
      - PAYMENT_PROCESSOR_DEFAULT_HEALTHCHECK_URL=http://payment-processor-default:8001/payments/service-health
      - PAYMENT_PROCESSOR_FALLBACK_HEALTHCHECK_URL=http://payment-processor-fallback:8002/payments/service-health

    networks:
      - rinha-network
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "30MB"
  api2:
    <<: *api
    hostname: api2
    environment:
      - REDIS_URI=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8001/payments
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8002/payments
      - PAYMENT_PROCESSOR_DEFAULT_HEALTHCHECK_URL=http://payment-processor-default:8001/payments/service-health
      - PAYMENT_PROCESSOR_FALLBACK_HEALTHCHECK_URL=http://payment-processor-fallback:8002/payments/service-health


  redis:
    image: redis:8.0-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - rinha-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"

networks:
  rinha-network:
    driver: bridge
  payment-processor:
    external: true

volumes:
  postgres-data:
  dragonfly-data:
