services:
  nginx:
    image: nginx:1.29.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "32MB"

  api1: &api
    image: matheusbaptistella/client-rs:latest
    hostname: api1
    expose:
      - 3000
    networks:
      - backend
      - payment-processor
    depends_on:
      - database
    command: sh -c "sleep 5 && /bin/server"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "96MB"

  api2:
    <<: *api
    hostname: api2

  database:
    image: matheusbaptistella/database-rs:latest
    hostname: database
    expose:
      - 6379
    networks:
      - backend
    command: sh -c "/bin/server"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "126MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
