services:

  redis:
    image: redis:8.0.3-alpine
    hostname: redis
    networks:
      - local_network
    command: redis-server /etc/redis/redis.conf --save "" --appendonly no --maxclients 20000 
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '40MB'
    
  api1: &api
    image: gedun/mandioca-cozidinha-api:latest
    hostname: api1
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 120M
    environment:
      Services__PaymentProcessor__Default: "http://payment-processor-default:8080"
      Services__PaymentProcessor__Fallback: "http://payment-processor-fallback:8080"
      Services__PaymentProcessor__Token: "123"
      Redis__Server: "redis:6379"
      QueueCapacity: "10000"
    ports:
      - "9990:8080"
    networks:
      - local_network
      - payment-processor 

  api2: 
    <<: *api
    hostname: api2
    ports:
      - "9991:8080"

  nginx:
    image: nginx:latest
    networks:
      - local_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

networks:
  local_network:
    driver: bridge
  payment-processor:
    external: true