services:
  nginx:
    image: nginx:1.29.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "32MB"

  api1: &api
    image: matheusbaptistella/client-full:latest
    hostname: api1
    expose:
      - 3000
    environment:
      - PEER_URL=http://api2:3000
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "159MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - PEER_URL=http://api1:3000


networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
