services:
  redis:
    image: redis:8.0.3-alpine
    container_name: cgb-redis
    restart: unless-stopped
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxclients",
        "10000",
        "--tcp-backlog",
        "511",
        "--timeout",
        "0",
        "--tcp-keepalive",
        "300"
      ]
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "65MB"

  api1:
    image: cicerocg/rinha-v1:v2.0
    platform: linux/amd64
    container_name: cgb-api1
    networks:
      - backend
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - MODE=api
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '70MB'

  api2:
    image: cicerocg/rinha-v1:v2.0
    platform: linux/amd64
    container_name: cgb-api2
    networks:
      - backend
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - MODE=api
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '70MB'

  worker:
    image: cicerocg/rinha-v1:v2.0
    platform: linux/amd64
    container_name: cgb-worker
    networks:
      - backend
      - payment-processor
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis:6379
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
      - MODE=worker
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '105MB'

  nginx:
    image: nginx:1.27.0-alpine
    container_name: cgb-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '40MB'

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true