x-api-templates:
  app: &api-template
    image: mrprince2/rinha-java-1:latest
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    environment:
      JAVA_OPTS: >-
        -Xms70m -Xmx120m
        -Xscmx40m
        -Xshareclasses:cacheDir=/tmp
        -XX:+IdleTuningGcOnIdle
        -XX:+UseContainerSupport
        -Xtune:virtualized
        -Xquickstart
        -Xgc:concurrentScavenge
        -Xdisableexplicitgc
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: "155MB"

services:
  api-1:
    <<: *api-template
    container_name: api-1
    hostname: api-1

  api-2:
    <<: *api-template
    container_name: api-2
    hostname: api-2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: "30MB"
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: "10MB"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
