services:
  nginx:
    container_name: nginx
    depends_on:
      - api_1
      - api_2
      - worker
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "25MB"

  api_1:
    container_name: api_1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: filipebafica/rinha-backend-2025-go-api:latest
    environment:
      APP_PORT: 8000
      REDIS_ADDR: redis:6379
      QUEUE_NAME: payments_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789abcdef
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: rinha_backend
      POSTGRES_SSL_MODE: disable
    volumes:
      - .:/app/
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "65MB"

  api_2:
    container_name: api_2
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: filipebafica/rinha-backend-2025-go-api:latest
    environment:
      APP_PORT: 8001
      REDIS_ADDR: redis:6379
      QUEUE_NAME: payments_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789abcdef
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: rinha_backend
      POSTGRES_SSL_MODE: disable
    volumes:
      - .:/app/
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "65MB"

  worker:
    container_name: worker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: filipebafica/rinha-backend-2025-go-worker:latest
    environment:
      REDIS_ADDR: redis:6379
      QUEUE_NAME: payments_queue
      WORKERS_NUMBER: 3
      MAX_RETRY: 10
      PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
      PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789abcdef
      POSTGRES_DB_HOST: postgres
      POSTGRES_DB_PORT: 5432
      POSTGRES_DB_NAME: rinha_backend
      POSTGRES_SSL_MODE: disable
    volumes:
      - .:/app/
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"

  redis:
    container_name: redis
    image: redis:8.2.0-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456789abcdef
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha_backend
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha_backend" ]
      interval: 2s
      timeout: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "105MB"

volumes:
  redis_data:
  postgres_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true