services:
  postgres-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rinha
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0 -c fsync=0 -c full_page_writes=0
    networks:
      - backend-db
      - payment-processor
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 15
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  redis:
    image: redis:7-alpine
    networks:
      - backend-db
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  backend-1:
    image: oornnery/rinha-backend-2025-python:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-db:5432/rinha
      - REDIS_URL=redis://redis:6379/0
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend-db
      - payment-processor
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"

  backend-2:
    image: oornnery/rinha-backend-2025-python:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres-db:5432/rinha
      - REDIS_URL=redis://redis:6379/0
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    depends_on:
      postgres-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend-db
      - payment-processor
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend-db
    ports:
      - "9999:9999"
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.04"
          memory: "10MB"

networks:
  payment-processor:
    external: true
    name: payment-processor
  backend-db:
    driver: bridge
