services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

  app1: &app1
    image: laurosantana/backend-rinha-2025:0.2
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=9090
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - MIGRATE=1
      - CONSUMER=0
    networks:
      - backend
    depends_on:
      - rabbitmq
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  app2: 
    <<: *app1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=9090
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - MIGRATE=0
      - CONSUMER=0

  app3:
    <<: *app1
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - CONSUMER=1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "40MB"

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
     sh -c "rabbitmq-plugins disable --offline rabbitmq_prometheus && rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "55MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true