services:
  load-balancer:
    image: nginx:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-1
      - backend-2
    networks:
      - backend
      - payment-processor

  postgres:
    image: postgres:15
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "120MB"
    container_name: rinha2025-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: rinha2025
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./sql/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "rinha2025"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend

  backend-1:
    image: pedrohenriquea/rinha-2025:latest
    container_name: backend-1
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "85MB"
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://postgres:5432/rinha2025
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

  backend-2:
    image: pedrohenriquea/rinha-2025:latest
    container_name: backend-2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "85MB"
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - DB_URL=jdbc:postgresql://postgres:5432/rinha2025
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
