services:
  worker:
    image: arthurbpf/rinha-de-backend-2025-worker:latest
    hostname: worker
    restart: always
    environment:
      - PORT=3000
      - PAYMENT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PAYMENT_PROCESSOR_URL=http://payment-processor-fallback:8080
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 220M

  api1: &api-base
    image: arthurbpf/rinha-de-backend-2025-api:latest
    hostname: api1
    restart: always
    environment:
      - PORT=3000
      - WORKER_URL=http://worker:3000
    depends_on:
      - worker
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M

  api2:
    <<: *api-base
    hostname: api2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 50M

  lb:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - rinha-net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 30M

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
