x-api-template: &api-template
  image: passosmatheus/python-backend-rinha-api:tcp-client
  environment:
    - REDIS_HOST=redis-db
    - REDIS_PORT=6379
    - TCP_QUEUE_HOST=worker-3
    - TCP_QUEUE_PORT=8888
    - TCP_QUEUE_TIMEOUT=5.0
    - PORT=8080
  deploy:
    resources:
      limits:
        cpus: '0.4'
        memory: '70MB'
  sysctls:
    - net.core.somaxconn=65535
    - net.ipv4.tcp_tw_reuse=1

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-db
    command:
      - redis-server
      - --save ""
      - --appendonly no
      - --maxclients 10000
      - --tcp-backlog 511
      - --tcp-keepalive 60
      - --timeout 0
      - --maxmemory 45mb
      - --maxmemory-policy allkeys-lru
    networks:
      - app
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: '65MB'

  api-1:
    <<: *api-template
    container_name: api-1
    networks:
      - app
    depends_on:
      - redis
      - worker-3

  api-2:
    <<: *api-template
    container_name: api-2
    networks:
      - app
    depends_on:
      - redis
      - worker-3

  worker-3:
    image: passosmatheus/python-backend-rinha-worker:tcp-server
    container_name: worker-3
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080/payments
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080/payments
      - TCP_QUEUE_HOST=0.0.0.0
      - TCP_QUEUE_PORT=8888
      - NUM_WORKERS=4
      - CONCURRENT_REQUESTS=8
      - MAX_BATCH_SIZE=250
    ports:
      - "8888:8888"
    networks:
      - app
      - payment-processor
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '70MB'
    sysctls:
      - net.core.somaxconn=65535
      - net.ipv4.tcp_tw_reuse=1
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8888"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  load-balancer:
    image: nginx:1.25-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api-1:
        condition: service_started
      api-2:
        condition: service_started
    ports:
      - "9999:9999"
      - "9901:9901"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.18'
          memory: '65MB'
    sysctls:
      - net.core.somaxconn=131072
      - net.ipv4.tcp_tw_reuse=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
