x-api_template: &api
  image: ghcr.io/lothyriel/rinha_2025:v0.5.0
  volumes:
    - uds:/var/run
  command: ["-m", "api"]
  depends_on:
    - worker
  environment:
    RUST_LOG: "info"
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "80MB"

services:
  lb:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - uds:/var/run
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api0
      - api1
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  api0:
    <<: *api
    environment:
      API_N: "0"
      RUST_LOG: "info"
      WORKER_SOCKET: "/var/run/worker.sock"

  api1:
    <<: *api
    environment:
      API_N: "1"
      RUST_LOG: "info"
      WORKER_SOCKET: "/var/run/worker.sock"

  worker:
    image: ghcr.io/lothyriel/rinha_2025:v0.5.0
    command: ["-m", "worker"]
    networks:
      - payment-processor
    volumes:
      - uds:/var/run
    environment:
      WORKER_SOCKET: "/var/run/worker.sock"
      RUST_LOG: "info"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
