version: '3.8'

services:
  api01:
    image: suntzu12/quarkus-payment-router-java-21:2.0.0
    container_name: api01
    depends_on:
      - payment-router-db
    hostname: api01
    ports:
      - "8081:8080"
    environment:
      BATCH_SIZE: 600
      PROCESS_THREAD_POOL: 20
      DB_USER: postgres
      DB_PASS: postgres
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
      QUARKUS_REST_CLIENT_FALLBACK_API_URL: http://payment-processor-fallback:8080
      DB_URL: vertx-reactive:postgresql://payment-router-db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - payment-router
      - payment-processor

  api02:
    image: suntzu12/quarkus-payment-router-java-21:2.0.0
    container_name: api02
    depends_on:
      - payment-router-db
    hostname: api02
    ports:
      - "8082:8080"
    environment:
      BATCH_SIZE: 600
      PROCESS_THREAD_POOL: 20
      DB_USER: postgres
      DB_PASS: postgres
      QUARKUS_REST_CLIENT_DEFAULT_API_URL: http://payment-processor-default:8080
      QUARKUS_REST_CLIENT_FALLBACK_API_URL: http://payment-processor-fallback:8080
      DB_URL: vertx-reactive:postgresql://payment-router-db:5432/rinha
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"
    networks:
      - payment-router
      - payment-processor

  payment-router-db:
    image: postgres:17-alpine
    container_name: payment-router-db
    hostname: payment-router-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "100MB"
    networks:
      - payment-router

  load_balancer:
    image: nginx:latest
    container_name: load_balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"
    networks:
      - payment-router

networks:
  payment-router:
    driver: bridge
  payment-processor:
    external: true