services:
  api1: &api1
    image: rmac737/jacarerj-rinha-backend:latest
    pull_policy: always
    hostname: api1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__Redis: redis:6379
      ProcessadorPagamentoPrincipal__BaseUrl: http://payment-processor-default:8080
      ProcessadorPagamentoFallback__BaseUrl: http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "75MB"
  api2:
    <<: *api1
    hostname: api2
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__Redis: redis:6379
      ProcessadorPagamentoPrincipal__BaseUrl: http://payment-processor-default:8080
      ProcessadorPagamentoFallback__BaseUrl: http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
  haproxy:
    image: haproxy:2.9
    ports:
      - "9999:9999"
    networks:
      - backend
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ulimits:
      nofile: 200000
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100M"
networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true