version: "3.9"
services:
  backend1:
    image: mathauscm/rinha-backend:latest
    hostname: backend1
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "125MB"
    networks:
      - internal
      - payment-processor

  backend2:
    image: mathauscm/rinha-backend:latest
    hostname: backend2
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - UV_THREADPOOL_SIZE=32
      - PORT=9999
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "125MB"
    networks:
      - internal
      - payment-processor

  redis:
    image: redis:7-alpine
    hostname: redis
    command: [
      "redis-server",
      "--appendonly", "no",
      "--save", "",
      "--maxmemory", "45mb",
      "--maxmemory-policy", "noeviction",
      "--tcp-keepalive", "60",
      "--timeout", "0",
      "--tcp-backlog", "511",
      "--databases", "1"
    ]
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - internal

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
    networks:
      - internal

networks:
  internal:
    driver: bridge
  payment-processor:
    external: true
    driver: bridge