services:
  nginx:
    image: nginx:alpine
    container_name: nginx-lb
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - api-2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"

  redis:
    image: redis:8.0.3
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "40MB"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --maxmemory 35mb --maxmemory-policy allkeys-lru

  api-1: &api
    image: kauska/rinha-backend-2025:1.1.0
    container_name: api-1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    restart: unless-stopped
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"

  api-2:
    <<: *api
    container_name: api-2

volumes:
  redis-data:

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true