services:
  api1: &api
    image: lhuizf/rinha-de-backend-2025-bun:1.8.0
    hostname: api1
    container_name: api1
    environment:
      - REDIS_URL=/tmp/sockets/redis.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/sockets/api1.sock
    volumes:
      - sockets:/tmp/sockets
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "135MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    environment:
      - REDIS_URL=/tmp/sockets/redis.sock
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SOCKET_PATH=/tmp/sockets/api2.sock

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: >
      sh -c "mkdir -p /tmp/sockets &&
      chmod 777 /tmp/sockets &&
      redis-server
      --save ''
      --appendonly no
      --maxclients 20000
      --tcp-backlog 511
      --dynamic-hz yes
      --unixsocket /tmp/sockets/redis.sock
      --unixsocketperm 777"
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - sockets:/tmp/sockets
    healthcheck:
      test: ["CMD", "redis-cli", "-s", "/tmp/sockets/redis.sock", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "65MB"

  load-balancer:
    image: nginx:1.25.2-alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "15MB"

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets:
