version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

  api1: &api
    image: matheuspieropan/rinhabackend2025:achoquefoi
    depends_on:
      redis:
        condition: service_healthy
    hostname: api1
    networks:
      - backend
      - payment-processor
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "140MB"

  api2:
    <<: *api
    hostname: api2
    ports:
      - "8081:8080"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: [
      "redis-server",
      "--save", "",
      "--appendonly", "no",
      "--databases", "1",
      "--loglevel", "warning",
      "--logfile", "/dev/null",
      "--tcp-keepalive", "60"
    ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "40MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true